[settings]
rust.cargo_home  = '.local/share/cargo'
rust.rustup_home = '.local/share/rustup'
idiomatic_version_file_enable_tools = ['node', 'ruby']

[tools]
## Binaries and TUIs
atuin       = 'latest'
bat         = 'latest'
bottom      = 'latest'
delta       = 'latest'
direnv      = 'latest'
eza         = 'latest'
fd          = 'latest'
fzf         = 'latest'
github-cli  = 'latest'
glow        = 'latest'
gum         = 'latest'
jq          = 'latest'
just        = 'latest'
lazydocker  = 'latest'
lazygit     = 'latest'
neovim      = 'latest'
opencode    = 'latest'
resvg       = 'latest'
ripgrep     = 'latest'
starship    = 'latest'
tree-sitter = 'latest'
uv          = 'latest'
yazi        = 'latest'
zoxide      = 'latest'

'github:rgwood/systemctl-tui' = 'latest'
'pipx:sqlit-tui'              = 'latest'

## Languages
node   = 'lts'

## LSPs
marksman    = 'latest'
